### ISSUE TITLE
px units

### ISSUE THREAD

**Issue by tkornack** [storborg/axibot#33]
My drawing program (Sketch for macOS) decided to output SVG with px units.

1px = 1/96 in

It's a trivial thing to fix. I'll submit a pull request.

**Comment by storborg** [comment]
We intentionally left off px from the table of physical units, with the rationale that you usually want to auto-scale if px are used. However, it would be nice to have more explicit control of that, so I think a good solution would just be something like a ``dpi`` argument which can be optionally set. What do you think?

**Comment by storborg** [comment]
Actually, maybe a better option would just be an argument like ``--scale`` that could take float values or a value of ``fit`` (and maybe even ``crop``).

**Comment by tkornack** [comment]
In my case I prefer to draw with accurate dimensions and the SVG output just happens to be accurate in px units. Here's the relevant pull request: #35 .

I agree that adding a scale or fit option would be great.

**Comment by storborg** [comment]
Likewise, it's just frustrating that Sketch (and others) use px, since that seems like semantically the wrong unit for a physical drawing. It's less bad than it could be, since the SVG spec is pretty clear about 96px = 1in, but there are plenty of other things that are 72px = 1in by convention. Also, in practice, random vector art around the web, stock imagery sites, etc uses pixel dimensions that are all over the map.

I've merged that PR, and will look at some options for configurable scaling. Thanks.
